name: CI/CD Pipeline FIAP Sub Fase 5


on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin


      - name: Build and Push Docker Image
        run: |
          docker build -t lipegn/fiap-sub-fase-5:latest .
          docker push lipegn/fiap-sub-fase-5:latest


      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_NEW }}
          version: 1.21.0


      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml
